name: "haptic-feedback"

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    paths:
      - '.swiftlint.yml'
      - ".github/workflows/**"
      - "Package.swift"
      - "Source/**"
      - "Tests/**"

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
        env:
          DIFF_BASE: ${{ github.base_ref }}
  Latest:
    name: Test Latest (iOS)
    runs-on: macOS-12
    env:
      DEVELOPER_DIR: "/Applications/Xcode_14.1.app/Contents/Developer"
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: "OS=16.1,name=iPhone 14 Pro"
            name: "iOS"
            scheme: "HapticFeedback"
    steps:
      - uses: actions/checkout@v3
      - name: ${{ matrix.name }}
        run: xcodebuild -scheme "${{ matrix.scheme }}" -destination "${{ matrix.destination }}" clean
      